-- 01_warehouses.sql


USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS ONCOLAKE_LOAD_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60          -- seconds
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Ingestion / COPY / Snowpipe / Matillion loads';

CREATE WAREHOUSE IF NOT EXISTS ONCOLAKE_QUERY_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Analytics, Streamlit, Cortex, ad-hoc queries';

GRANT USAGE ON WAREHOUSE ONCOLAKE_LOAD_WH  TO ROLE ONCOLAKE_ENG;
GRANT USAGE ON WAREHOUSE ONCOLAKE_QUERY_WH TO ROLE ONCOLAKE_ENG;

